<link rel="stylesheet" href="style_code.css">
<div class="container">
    <div class="scrollable-content">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ut porttitor leo a diam sollicitudin tempor id eu. Sed arcu non odio euismod lacinia at. Platea dictumst quisque sagittis purus. Dui sapien eget mi proin sed libero. A condimentum vitae sapien pellentesque. Neque viverra justo nec ultrices dui sapien eget. Dictum varius duis at consectetur lorem. Non diam phasellus vestibulum lorem. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. A condimentum vitae sapien pellentesque habitant morbi tristique. Vivamus arcu felis bibendum ut tristique et egestas quis. Urna nunc id cursus metus aliquam eleifend mi in nulla. Scelerisque felis imperdiet proin fermentum leo vel orci. Rutrum quisque non tellus orci. Vel pharetra vel turpis nunc eget lorem dolor. Urna condimentum mattis pellentesque id nibh tortor. A iaculis at erat pellentesque adipiscing. Aliquam faucibus purus in massa.
        <br>
        Nec dui nunc mattis enim ut tellus elementum. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Hac habitasse platea dictumst quisque sagittis. Viverra aliquet eget sit amet tellus. Quis blandit turpis cursus in hac habitasse platea dictumst quisque. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Pulvinar pellentesque habitant morbi tristique senectus et netus et.
        <br>
        In pellentesque massa placerat duis ultricies lacus. Pretium nibh ipsum consequat nisl vel pretium. Convallis tellus id interdum velit laoreet id. Lorem ipsum dolor sit amet consectetur. Magna eget est lorem ipsum dolor sit amet consectetur. Suscipit adipiscing bibendum est ultricies integer. Nisi est sit amet facilisis. Metus dictum at tempor commodo ullamcorper. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Sed nisi lacus sed viverra tellus in hac habitasse. Ut porttitor leo a diam sollicitudin tempor id eu nisl. In hac habitasse platea dictumst vestibulum rhoncus est. Consectetur adipiscing elit duis tristique sollicitudin. Diam quam nulla porttitor massa id neque aliquam vestibulum.
        <br>
        Pellentesque elit eget gravida cum sociis natoque penatibus et. Rutrum tellus pellentesque eu tincidunt tortor. Arcu cursus vitae congue mauris rhoncus aenean. Volutpat diam ut venenatis tellus. Faucibus et molestie ac feugiat sed lectus vestibulum mattis. Felis eget nunc lobortis mattis aliquam. In fermentum posuere urna nec tincidunt praesent semper feugiat. Vel fringilla est ullamcorper eget nulla facilisi etiam. Ut eu sem integer vitae justo eget magna fermentum. Curabitur vitae nunc sed velit dignissim sodales ut eu. Ut sem viverra aliquet eget sit amet. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra.
        <br>
        Vulputate eu scelerisque felis imperdiet proin fermentum leo. Mauris in aliquam sem fringilla ut morbi tincidunt augue interdum. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Tristique magna sit amet purus gravida. Mauris nunc congue nisi vitae suscipit tellus. Enim eu turpis egestas pretium aenean pharetra magna ac. Vitae tortor condimentum lacinia quis vel eros donec ac. A arcu cursus vitae congue mauris. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Magna sit amet purus gravida quis. Vitae tempus quam pellentesque nec nam aliquam. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Nulla pharetra diam sit amet nisl. Nam libero justo laoreet sit amet. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Aliquam id diam maecenas ultricies mi. Sollicitudin nibh sit amet commodo. Lacus laoreet non curabitur gravida arcu ac tortor.
        Erat nam at lectus urna duis. Volutpat sed cras ornare arcu dui. Ac ut consequat semper viverra nam libero justo laoreet sit. Ut tristique et egestas quis ipsum suspendisse. Magna fringilla urna porttitor rhoncus dolor purus non enim. Fames ac turpis egestas integer eget aliquet. Id volutpat lacus laoreet non curabitur gravida arcu. Mi eget mauris pharetra et. Vitae semper quis lectus nulla at volutpat. Commodo nulla facilisi nullam vehicula ipsum a. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Sit amet est placerat in. Egestas fringilla phasellus faucibus scelerisque eleifend. Velit aliquet sagittis id consectetur. Amet dictum sit amet justo donec. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Velit euismod in pellentesque massa.
        <br>
        Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Sagittis purus sit amet volutpat consequat mauris nunc. Magna ac placerat vestibulum lectus mauris. Aliquam etiam erat velit scelerisque. Mi ipsum faucibus vitae aliquet nec. Aenean et tortor at risus viverra. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Tristique nulla aliquet enim tortor at auctor urna nunc. Urna neque viverra justo nec ultrices dui sapien eget. Rhoncus mattis rhoncus urna neque viverra. Vitae justo eget magna fermentum iaculis eu non diam. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Dignissim enim sit amet venenatis urna cursus. Nunc scelerisque viverra mauris in. Nunc sed blandit libero volutpat. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Porttitor rhoncus dolor purus non. Sit amet cursus sit amet dictum. Elit ullamcorper dignissim cras tincidunt.
        <code>
            Proin libero nunc consequat interdum varius sit amet mattis vulputate. Purus in mollis nunc sed. Mi in nulla posuere sollicitudin aliquam ultrices. Accumsan tortor posuere ac ut. Id nibh tortor id aliquet lectus proin nibh nisl. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Eget dolor morbi non arcu risus. Malesuada fames ac turpis egestas maecenas pharetra convallis. Sit amet nisl purus in mollis nunc sed id semper. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Neque gravida in fermentum et sollicitudin ac orci. Mi proin sed libero enim sed faucibus. Amet venenatis urna cursus eget nunc scelerisque viverra mauris. Risus pretium quam vulputate dignissim suspendisse in est ante in. In ante metus dictum at tempor commodo ullamcorper a.
            <br>
            <br>
            Enim nec dui nunc mattis enim ut tellus. Viverra justo nec ultrices dui sapien. Auctor augue mauris augue neque gravida in fermentum et sollicitudin. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Pulvinar mattis nunc sed blandit. Pharetra et ultrices neque ornare aenean euismod. Natoque penatibus et magnis dis. Arcu non odio euismod lacinia at quis risus sed. Elit eget gravida cum sociis natoque. Lacus sed viverra tellus in hac. Nisl vel pretium lectus quam. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Pellentesque habitant morbi tristique senectus. Tincidunt tortor aliquam nulla facilisi cras. Arcu bibendum at varius vel pharetra. Pretium quam vulputate dignissim suspendisse in. Bibendum neque egestas congue quisque egestas diam.
            <br>
            Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Amet aliquam id diam maecenas ultricies mi eget mauris pharetra. Nunc faucibus a pellentesque sit amet. Dolor morbi non arcu risus quis varius quam quisque. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Fermentum posuere urna nec tincidunt. Elementum nibh tellus molestie nunc non blandit massa enim nec. Et leo duis ut diam quam nulla porttitor. Cursus risus at ultrices mi tempus imperdiet nulla.
            <p>Beispieltext ...</p>
        </code>
    </div>
    <div class="top-fade"></div>
    <div class="bottom-fade"></div>
</div>